// src/app/core/layout/header.component.ts
import { Component, inject } from "@angular/core";
import { UserService } from "../auth/services/user.service";
import { RouterLink, RouterLinkActive } from "@angular/router";
import { AsyncPipe } from "@angular/common";
import { IfAuthenticatedDirective } from "../auth/if-authenticated.directive";

@Component({
  selector: "app-layout-header",
  templateUrl: "./header.component.html",
  imports: [RouterLinkActive, RouterLink, AsyncPipe, IfAuthenticatedDirective],
})
export class HeaderComponent {
  currentUser$ = inject(UserService).currentUser;
  isMobileMenuOpen = false;

  toggleMobileMenu(): void {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  closeMobileMenu(): void {
    this.isMobileMenuOpen = false;
  }
}

<nav class="navbar navbar-light">
  <div class="container">
    <a class="navbar-brand" routerLink="/">conduit</a>

    <!-- Mobile menu toggle button -->
    <button
      class="navbar-toggler d-md-none"
      type="button"
      (click)="toggleMobileMenu()"
      [attr.aria-expanded]="isMobileMenuOpen"
      aria-controls="navbarNav"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon">
        <i class="ion-navicon-round" [class.rotate]="isMobileMenuOpen"></i>
      </span>
    </button>

    <!-- Navigation menu -->
    <div class="navbar-collapse" [class.show]="isMobileMenuOpen" id="navbarNav">
      <!-- Show this for logged out users -->
      <ul *ifAuthenticated="false" class="nav navbar-nav pull-xs-right">
        <li class="nav-item">
          <a
            class="nav-link interactive-link"
            routerLink="/"
            (click)="closeMobileMenu()"
          >
            Home
          </a>
        </li>

        <li class="nav-item">
          <a
            class="nav-link interactive-link"
            routerLink="/login"
            routerLinkActive="active"
            (click)="closeMobileMenu()"
          >
            Sign in
          </a>
        </li>

        <li class="nav-item">
          <a
            class="nav-link interactive-link"
            routerLink="/register"
            routerLinkActive="active"
            (click)="closeMobileMenu()"
          >
            Sign up
          </a>
        </li>
      </ul>

      <!-- Show this for logged in users -->
      <ul *ifAuthenticated="true" class="nav navbar-nav pull-xs-right">
        <li class="nav-item">
          <a
            class="nav-link interactive-link"
            routerLink="/"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{ exact: true }"
            (click)="closeMobileMenu()"
          >
            Home
          </a>
        </li>

        <li class="nav-item">
          <a
            class="nav-link interactive-link"
            routerLink="/editor"
            routerLinkActive="active"
            (click)="closeMobileMenu()"
          >
            <i class="ion-compose"></i>&nbsp;New Article
          </a>
        </li>

        <li class="nav-item">
          <a
            class="nav-link interactive-link"
            routerLink="/settings"
            routerLinkActive="active"
            (click)="closeMobileMenu()"
          >
            <i class="ion-gear-a"></i>&nbsp;Settings
          </a>
        </li>

        @if (currentUser$ | async; as currentUser) {
          <li class="nav-item">
            <a
              class="nav-link interactive-link"
              [routerLink]="['/profile', currentUser.username]"
              routerLinkActive="active"
              (click)="closeMobileMenu()"
            >
              @if (currentUser.image) {
                <img [src]="currentUser.image" class="user-pic" />
              }
              {{ currentUser.username }}
            </a>
          </li>
        }
      </ul>
    </div>
  </div>
</nav>

// src/core/layout/Header.tsx
import React from "react";
import { Link, NavLink } from "react-router-dom";
import { useAuth } from "../auth/useAuth";

const Header: React.FC = () => {
  const { user, isAuthenticated } = useAuth();

  return (
    <nav className="navbar navbar-light">
      <div className="container">
        <Link className="navbar-brand" to="/">
          conduit
        </Link>
        <ul className="nav navbar-nav pull-xs-right">
          <li className="nav-item">
            <NavLink className="nav-link" to="/">
              Home
            </NavLink>
          </li>
          {isAuthenticated && user ? (
            <>
              <li className="nav-item">
                <NavLink className="nav-link" to="/editor">
                  <i className="ion-compose"></i>&nbsp;New Article
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink className="nav-link" to="/settings">
                  <i className="ion-gear-a"></i>&nbsp;Settings
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink className="nav-link" to={`/profile/${user.username}`}>
                  <img src={user.image} className="user-pic" alt="" />
                  {user.username}
                </NavLink>
              </li>
            </>
          ) : (
            <>
              <li className="nav-item">
                <NavLink className="nav-link" to="/login">
                  Sign in
                </NavLink>
              </li>
              <li className="nav-item">
                <NavLink className="nav-link" to="/register">
                  Sign up
                </NavLink>
              </li>
            </>
          )}
        </ul>
      </div>
    </nav>
  );
};

export default Header;
